// This file is fully generated by running parsergen v1.6.2
// with grammer definition file "grammar.txt"

#ifndef ParserIdDef_H
#define ParserIdDef_H

#include <bux/LexBase.h>    // bux::TOKENGEN_LB

namespace json {

// Token Id Constants
enum
{
    TID_LEX_Error       = bux::TOKENGEN_LB+0,	// $Error
    TID_LEX_Float       = bux::TOKENGEN_LB+1,	// $Float
    TID_LEX_Num         = bux::TOKENGEN_LB+2,	// $Num
    TID_LEX_Spaces      = bux::TOKENGEN_LB+3,	// $Spaces
    TID_LEX_String      = bux::TOKENGEN_LB+4,	// $String
    TID_KEYWORD_false   = bux::TOKENGEN_LB+5,	// "false"
    TID_KEYWORD_null    = bux::TOKENGEN_LB+6,	// "null"
    TID_KEYWORD_true    = bux::TOKENGEN_LB+7,	// "true"
    TID_UB_
};

} // namespace json

#endif // ParserIdDef_H
