// This file is fully generated by running parsergen
// with grammer definition file "grammar.txt"

#ifndef ParserH
#define ParserH

#include <bux/LR1.h>

namespace json {

// %PRECLASSDECL expanded BEGIN
extern int errors;
// %PRECLASSDECL expanded END

class C_Parser: public bux::LR1::C_Parser
{
public:

    // Ctor
    C_Parser();
};

} // namespace json

#endif // ParserH
