#!/usr/bin/env bash
if [[ -z "$TOOL_ROOT" ]]; then
    TOOL_ROOT=../../parsergen
fi
if [[ -z "$PARSERGEN_DIR" ]]; then
    PARSERGEN_DIR=$TOOL_ROOT/ParserGen
fi
if [[ -z "$SCANNERGEN_DIR" ]]; then
    SCANNERGEN_DIR=$TOOL_ROOT/ScannerGen
fi
$PARSERGEN_DIR/parsergen grammar.txt Parser tokens.txt && \
$SCANNERGEN_DIR/scannergen Scanner "$SCANNERGEN_DIR/RE_Suite.txt" tokens.txt
