// This file is fully generated by running scannergen v1.7.7

// Token-def %HEADERS_FOR_CPP begins
#include "ParserIdDef.h"
// Grammar %HEADERS_FOR_SCANNER_CPP begins
#include "JsonObjs.h"   // json::jint, json::jfloat
#include <charconv>     // std::from_chars()
// Grammar %HEADERS_FOR_SCANNER_CPP ends
using namespace json;
// Token-def %HEADERS_FOR_CPP ends

#include "Scanner.h"

namespace {

// ASCII TABLE:
//  0: \x00\x01\x02\x03\x04\x05\x06\a\b\t\n\v\f\r\x0e\x0f\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f
// 20:  !\"#$%&\'()*+,-./0123456789:;<=>?
// 40: @ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_
// 60: `abcdefghijklmnopqrstuvwxyz{|}~\x7f
constinit const C_JSONScanner::C_GotoPair
GOTO_STATE1[6] ={
    {'\t', 3},
    {'\n', std::numeric_limits<int8_t>::max()},
    {'\v', 3},
    {'\x0e', std::numeric_limits<int8_t>::max()},
    {' ', 3},
    {'!', std::numeric_limits<int8_t>::max()}},
GOTO_STATE2[19] ={
    {'\t', 3},
    {'\n', std::numeric_limits<int8_t>::max()},
    {'\v', 3},
    {'\x0e', std::numeric_limits<int8_t>::max()},
    {' ', 3},
    {'!', std::numeric_limits<int8_t>::max()},
    {'\"', 11},
    {'#', std::numeric_limits<int8_t>::max()},
    {'.', 12},
    {'/', std::numeric_limits<int8_t>::max()},
    {'0', 2},
    {'1', 10},
    {':', std::numeric_limits<int8_t>::max()},
    {'f', 14},
    {'g', std::numeric_limits<int8_t>::max()},
    {'n', 15},
    {'o', std::numeric_limits<int8_t>::max()},
    {'t', 17},
    {'u', std::numeric_limits<int8_t>::max()}},
GOTO_STATE3[11] ={
    {' ', 20},
    {'\"', 5},
    {'#', 20},
    {'0', 34},
    {':', 20},
    {'A', 34},
    {'G', 20},
    {'\\', 19},
    {']', 20},
    {'a', 34},
    {'g', 20}},
GOTO_STATE4[11] ={
    {' ', 20},
    {'\"', 5},
    {'#', 20},
    {'0', 35},
    {':', 20},
    {'A', 35},
    {'G', 20},
    {'\\', 19},
    {']', 20},
    {'a', 35},
    {'g', 20}},
GOTO_STATE5[11] ={
    {' ', 20},
    {'\"', 5},
    {'#', 20},
    {'0', 36},
    {':', 20},
    {'A', 36},
    {'G', 20},
    {'\\', 19},
    {']', 20},
    {'a', 36},
    {'g', 20}},
GOTO_STATE6[5] ={
    {' ', 20},
    {'\"', 5},
    {'#', 20},
    {'\\', 19},
    {']', 20}},
GOTO_STATE7[20] ={
    {'\"', 20},
    {'#', std::numeric_limits<int8_t>::max()},
    {'\'', 20},
    {'(', std::numeric_limits<int8_t>::max()},
    {'\\', 20},
    {']', std::numeric_limits<int8_t>::max()},
    {'a', 20},
    {'c', std::numeric_limits<int8_t>::max()},
    {'f', 20},
    {'g', std::numeric_limits<int8_t>::max()},
    {'n', 20},
    {'o', std::numeric_limits<int8_t>::max()},
    {'r', 20},
    {'s', std::numeric_limits<int8_t>::max()},
    {'t', 20},
    {'u', 23},
    {'v', 20},
    {'w', std::numeric_limits<int8_t>::max()},
    {'x', 26},
    {'y', std::numeric_limits<int8_t>::max()}},
GOTO_STATE8[6] ={
    {'+', 13},
    {',', std::numeric_limits<int8_t>::max()},
    {'-', 13},
    {'.', std::numeric_limits<int8_t>::max()},
    {'0', 9},
    {':', std::numeric_limits<int8_t>::max()}},
GOTO_STATE9[8] ={
    {'.', 1},
    {'/', std::numeric_limits<int8_t>::max()},
    {'0', 1},
    {':', std::numeric_limits<int8_t>::max()},
    {'E', 18},
    {'F', std::numeric_limits<int8_t>::max()},
    {'e', 18},
    {'f', std::numeric_limits<int8_t>::max()}},
GOTO_STATE10[8] ={
    {'.', 1},
    {'/', std::numeric_limits<int8_t>::max()},
    {'0', 4},
    {':', std::numeric_limits<int8_t>::max()},
    {'E', 18},
    {'F', std::numeric_limits<int8_t>::max()},
    {'e', 18},
    {'f', std::numeric_limits<int8_t>::max()}},
GOTO_STATE11[2] ={
    {'0', 1},
    {':', std::numeric_limits<int8_t>::max()}},
GOTO_STATE12[6] ={
    {'0', 1},
    {':', std::numeric_limits<int8_t>::max()},
    {'E', 18},
    {'F', std::numeric_limits<int8_t>::max()},
    {'e', 18},
    {'f', std::numeric_limits<int8_t>::max()}},
GOTO_STATE13[2] ={
    {'0', 9},
    {':', std::numeric_limits<int8_t>::max()}},
GOTO_STATE14[6] ={
    {'0', 24},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 24},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 24},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE15[6] ={
    {'0', 25},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 25},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 25},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE16[6] ={
    {'0', 27},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 27},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 27},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE17[6] ={
    {'0', 32},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 32},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 32},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE18[6] ={
    {'0', 33},
    {':', std::numeric_limits<int8_t>::max()},
    {'A', 33},
    {'G', std::numeric_limits<int8_t>::max()},
    {'a', 33},
    {'g', std::numeric_limits<int8_t>::max()}},
GOTO_STATE19[2] ={
    {'a', 21},
    {'b', std::numeric_limits<int8_t>::max()}},
GOTO_STATE20[2] ={
    {'e', 6},
    {'f', std::numeric_limits<int8_t>::max()}},
GOTO_STATE21[2] ={
    {'e', 8},
    {'f', std::numeric_limits<int8_t>::max()}},
GOTO_STATE22[2] ={
    {'l', 7},
    {'m', std::numeric_limits<int8_t>::max()}},
GOTO_STATE23[2] ={
    {'l', 28},
    {'m', std::numeric_limits<int8_t>::max()}},
GOTO_STATE24[2] ={
    {'l', 29},
    {'m', std::numeric_limits<int8_t>::max()}},
GOTO_STATE25[2] ={
    {'r', 16},
    {'s', std::numeric_limits<int8_t>::max()}},
GOTO_STATE26[2] ={
    {'s', 31},
    {'t', std::numeric_limits<int8_t>::max()}},
GOTO_STATE27[2] ={
    {'u', 22},
    {'v', std::numeric_limits<int8_t>::max()}},
GOTO_STATE28[2] ={
    {'u', 30},
    {'v', std::numeric_limits<int8_t>::max()}};
// Token-def %LOCAL_ACTION_DEFS begins
// Grammar %LOCALS_FOR_SCANNER_CPP begins
template<class T_LexCh>
auto createFloatOrInt(const T_LexCh *c, size_t n)
{
    const auto s = bux::toString(c,0,n);
    const auto send = s.data() + s.size();
    jint i;
    if (std::from_chars(s.data(), send, i).ptr == send)
        return bux::C_ActionRet{TID_LEX_Num, bux::createLex(i)};
#if 1
    char *end;
    jfloat f = strtod(s.c_str(), &end);
    if (end != send)
        RUNTIME_ERROR("Not a float: {}", s);

    return bux::C_ActionRet{TID_LEX_Float, bux::createLex(f)};
#else
    jfloat f;
    auto t = std::from_chars(s.data(), send, f); // not supported by mainstream compilers yet
    if (t.ptr == send)
        return bux::C_ActionRet{TID_LEX_Float, bux::createLex(f)};

    if (t.ptr == s.data())
    {
        const auto ecode = make_error_code(t.ec);
        RUNTIME_ERROR("Error: {}:{}", ecode.category().name(), ecode.value());
    }
    else
        RUNTIME_ERROR("Not a float: {}", s);
#endif
}
// Grammar %LOCALS_FOR_SCANNER_CPP ends
// Token-def %LOCAL_ACTION_DEFS ends


constinit const C_JSONScanner::C_StateRec STATES[37] = {
    { GOTO_STATE2,	nullptr	},  // 0
    { GOTO_STATE12,	createFloatOrInt<bux::C_LexUTF32>	},  // 1
    { GOTO_STATE9,	createFloatOrInt<bux::C_LexUTF32>	},  // 2
    { GOTO_STATE1,	bux::createNothing<TID_LEX_Spaces,bux::C_LexUTF32>	},  // 3
    { GOTO_STATE10,	createFloatOrInt<bux::C_LexUTF32>	},  // 4
    { nullptr,	bux::createEscapeString<TID_LEX_String,bux::C_LexUTF32, 1, 1>	},  // 5
    { nullptr,	bux::createNothing<TID_KEYWORD_false,bux::C_LexUTF32>	},  // 6
    { nullptr,	bux::createNothing<TID_KEYWORD_null,bux::C_LexUTF32>	},  // 7
    { nullptr,	bux::createNothing<TID_KEYWORD_true,bux::C_LexUTF32>	},  // 8
    { GOTO_STATE13,	createFloatOrInt<bux::C_LexUTF32>	},  // 9
    { GOTO_STATE10,	createFloatOrInt<bux::C_LexUTF32>	},  // 10
    { GOTO_STATE6,	nullptr	},  // 11
    { GOTO_STATE11,	nullptr	},  // 12
    { GOTO_STATE13,	nullptr	},  // 13
    { GOTO_STATE19,	nullptr	},  // 14
    { GOTO_STATE27,	nullptr	},  // 15
    { GOTO_STATE28,	nullptr	},  // 16
    { GOTO_STATE25,	nullptr	},  // 17
    { GOTO_STATE8,	nullptr	},  // 18
    { GOTO_STATE7,	nullptr	},  // 19
    { GOTO_STATE6,	nullptr	},  // 20
    { GOTO_STATE23,	nullptr	},  // 21
    { GOTO_STATE24,	nullptr	},  // 22
    { GOTO_STATE14,	nullptr	},  // 23
    { GOTO_STATE15,	nullptr	},  // 24
    { GOTO_STATE16,	nullptr	},  // 25
    { GOTO_STATE17,	nullptr	},  // 26
    { GOTO_STATE18,	nullptr	},  // 27
    { GOTO_STATE26,	nullptr	},  // 28
    { GOTO_STATE22,	nullptr	},  // 29
    { GOTO_STATE21,	nullptr	},  // 30
    { GOTO_STATE20,	nullptr	},  // 31
    { GOTO_STATE6,	nullptr	},  // 32
    { GOTO_STATE3,	nullptr	},  // 33
    { GOTO_STATE4,	nullptr	},  // 34
    { GOTO_STATE5,	nullptr	},  // 35
    { GOTO_STATE6,	nullptr	}}; // 36

constinit const uint8_t GOTO_SIZE[37] = {
    19,	// 0
    6,	// 1
    8,	// 2
    6,	// 3
    8,	// 4
    0,	// 5
    0,	// 6
    0,	// 7
    0,	// 8
    2,	// 9
    8,	// 10
    5,	// 11
    2,	// 12
    2,	// 13
    2,	// 14
    2,	// 15
    2,	// 16
    2,	// 17
    6,	// 18
    20,	// 19
    5,	// 20
    2,	// 21
    2,	// 22
    6,	// 23
    6,	// 24
    6,	// 25
    6,	// 26
    6,	// 27
    2,	// 28
    2,	// 29
    2,	// 30
    2,	// 31
    5,	// 32
    11,	// 33
    11,	// 34
    11,	// 35
    5};	// 36

} // namespace

C_JSONScanner::C_JSONScanner(bux::I_Parser &parser):
    bux::C_ScannerImpl<uint8_t,int8_t,bux::C_LexUTF32>(parser)
{
    stateTables(STATES, GOTO_SIZE);
}
